apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: reverseproxy 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reverseproxy 
    spec:
      containers:
        - name: reverseproxy 
          image: andrewklazinga.azurecr.io/reverseproxy
          ports:
          - containerPort: 80